services:
  web:
    image: proxyserver # Замените на ваше изображение ASP.NET
    build:
      context: .
      dockerfile: ProxyServer/Dockerfile # Укажите путь к вашему Dockerfile
    ports:
      - "7176:7176"
      - "7177:7177" # Проброс порта, измените при необходимости
    environment:
      - REDIS_CONNECTION=redis:6379 # Настройка подключения к Redis
      - POSTGRES_CONNECTION=Host=postgres;Database=ProxyServerData;Username=postgres;Password=postgres
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres
    container_name: postgres 
    environment:
      - POSTGRES_DB=ProxyServerData
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432" # Проброс порта, если нужно подключаться извне контейнера

  redis: 
    image: redis:latest 
    container_name: redis_container 
    environment: 
      - REDIS_PASSWORD=my_redis_password 
      - REDIS_USER=my_user 
      - REDIS_USER_PASSWORD=my_user_password 
    ports: 
      - "6380:6379" 
    volumes: 
      - .RedisService/redisdata:/data 
    deploy: 
      resources: 
        limits: 
          cpus: '0.50' 
          memory: 512M 
        reservations: 
          cpus: '0.25' 
          memory: 256M 
    command: > 
      sh -c ' 
        mkdir -p /usr/local/etc/redis && 
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf && 
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf && 
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf && 
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf && 
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl && 
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl && 
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl 
      ' 
    healthcheck: 
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"] 
      interval: 30s 
      timeout: 10s 
      retries: 5 
    restart: unless-stopped 
    tty: true 
    stdin_open: true 

