-- PostgreSQL database dump

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE TABLE public."AccessProperties" (
    "AccessPropertyId" integer NOT NULL,
    "ServiceName" text NOT NULL,
    "AccessCount" integer NOT NULL
);
ALTER TABLE public."AccessProperties" OWNER TO postgres;

ALTER TABLE public."AccessProperties" ALTER COLUMN "AccessPropertyId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AccessProperties_AccessPropertyId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

COPY public."AccessProperties" ("AccessPropertyId", "ServiceName", "AccessCount") FROM stdin;
0	A05_EGRNI_WGS84	20
1	A01_ZIS_WGS84	20
2	A06_ATE_TE_WGS84	20
3	C01_Belarus_WGS84	1000
\.

SELECT pg_catalog.setval('public."AccessProperties_AccessPropertyId_seq"', 1, false);

ALTER TABLE ONLY public."AccessProperties"
    ADD CONSTRAINT "PK_AccessProperties" PRIMARY KEY ("AccessPropertyId");

ALTER TABLE ONLY public."AccessProperties"
    ADD CONSTRAINT "ServiceName" UNIQUE ("ServiceName") INCLUDE ("ServiceName");